"""Fail a release when wheel or sdist contents escape the public allowlist."""

from __future__ import annotations

import argparse
import base64
import csv
import email.policy
import gzip
import hashlib
import stat
import struct
import tarfile
import unicodedata
import zipfile
import zlib
from collections.abc import Iterable, Sequence
from email.parser import BytesParser
from io import StringIO
from pathlib import Path, PurePosixPath

FORBIDDEN_COMPONENTS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "__pycache__",
    "node_modules",
    "venv",
}
FORBIDDEN_SUFFIXES = {".key", ".p12", ".pem", ".pfx", ".pyc", ".pyo"}
SENSITIVE_NAMES = {
    "credentials",
    "credentials.json",
    "id_dsa",
    "id_ed25519",
    "id_rsa",
    "secrets.json",
}
SDIST_TOP_LEVEL = {
    ".github",
    ".gitignore",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "LICENSE",
    "PKG-INFO",
    "README.md",
    "SECURITY.md",
    "action.yml",
    "docs",
    "packaging",
    "pyproject.toml",
    "scripts",
    "src",
    "tests",
    "uv.lock",
    "workbooklens.example.yml",
}
MAX_MEMBERS = 2_000
MAX_MEMBER_BYTES = 10 * 1024 * 1024
MAX_TOTAL_BYTES = 100 * 1024 * 1024
MAX_COMPRESSION_RATIO = 250.0
MAX_PATH_CHARACTERS = 260
MAX_ARCHIVE_BYTES = 100 * 1024 * 1024
MAX_TAR_STREAM_BYTES = MAX_TOTAL_BYTES + (MAX_MEMBERS + 4) * 1024
WINDOWS_DEVICE_NAMES = {
    "aux",
    "con",
    "nul",
    "prn",
    *(f"com{number}" for number in range(1, 10)),
    *(f"lpt{number}" for number in range(1, 10)),
    "com¹",
    "com²",
    "com³",
    "lpt¹",
    "lpt²",
    "lpt³",
}
WINDOWS_INVALID_CHARACTERS = frozenset('<>"|?*')
UV_BUILD_IGNORE_CONTENTS = frozenset({b"*", b"*\n", b"*\r\n"})


class ArtifactError(RuntimeError):
    """A built distribution contains unexpected or unsafe material."""


def _distribution_metadata(payload: bytes, source: str, version: str) -> None:
    try:
        message = BytesParser(policy=email.policy.default).parsebytes(payload)
    except (UnicodeError, ValueError) as exc:
        raise ArtifactError(f"cannot parse distribution metadata {source}: {exc}") from exc
    name = str(message.get("Name", "")).strip()
    actual_version = str(message.get("Version", "")).strip()
    canonical_name = "-".join(filter(None, name.replace("_", "-").replace(".", "-").split("-")))
    if canonical_name.casefold() != "workbooklens":
        raise ArtifactError(f"{source} has unexpected project name: {name!r}")
    if actual_version != version:
        raise ArtifactError(f"{source} has version {actual_version!r}, expected {version!r}")


def _validate_path(name: str) -> PurePosixPath:
    if (
        not name
        or "\x00" in name
        or chr(92) in name
        or len(name) > MAX_PATH_CHARACTERS
        or any(part in {"", ".", ".."} for part in name.split("/"))
    ):
        raise ArtifactError(f"non-portable archive member: {name!r}")
    path = PurePosixPath(name)
    if path.is_absolute():
        raise ArtifactError(f"unsafe archive member: {name!r}")
    lowered = [part.lower() for part in path.parts]
    for part in lowered:
        if (
            part in FORBIDDEN_COMPONENTS
            or part.startswith(".venv")
            or part.endswith("-venv")
            or part.startswith(".env")
        ):
            raise ArtifactError(f"forbidden environment/cache path in artifact: {name}")
        trimmed = part.rstrip(" .")
        device_stem = trimmed.split(".", 1)[0]
        if (
            ":" in part
            or any(character in WINDOWS_INVALID_CHARACTERS for character in part)
            or any(ord(character) < 32 for character in part)
            or len(part) > 255
            or trimmed != part
            or device_stem in WINDOWS_DEVICE_NAMES
        ):
            raise ArtifactError(f"Windows-unsafe archive member: {name}")
    basename = lowered[-1]
    if basename in SENSITIVE_NAMES or path.suffix.lower() in FORBIDDEN_SUFFIXES:
        raise ArtifactError(f"possible secret or generated bytecode in artifact: {name}")
    return path


def _check_sizes(members: Iterable[tuple[str, int]]) -> list[PurePosixPath]:
    checked: list[PurePosixPath] = []
    exact_names: set[str] = set()
    casefold_names: dict[str, str] = {}
    total_size = 0
    for index, (name, size) in enumerate(members, start=1):
        if index > MAX_MEMBERS:
            raise ArtifactError(f"artifact has more than {MAX_MEMBERS} members")
        if size < 0:
            raise ArtifactError(f"artifact member has a negative size: {name}")
        if size > MAX_MEMBER_BYTES:
            raise ArtifactError(f"artifact member exceeds {MAX_MEMBER_BYTES} bytes: {name}")
        member = _validate_path(name)
        canonical = member.as_posix()
        if canonical in exact_names:
            raise ArtifactError(f"duplicate archive member: {canonical}")
        folded = unicodedata.normalize("NFC", canonical).casefold()
        previous = casefold_names.get(folded)
        if previous is not None:
            raise ArtifactError(f"case-colliding archive members: {previous!r} and {canonical!r}")
        exact_names.add(canonical)
        casefold_names[folded] = canonical
        total_size += size
        if total_size > MAX_TOTAL_BYTES:
            raise ArtifactError(f"artifact exceeds {MAX_TOTAL_BYTES} total uncompressed bytes")
        checked.append(member)
    return checked


def _check_ancestor_conflicts(
    members: Sequence[PurePosixPath],
    directories: set[str],
) -> None:
    names = {member.as_posix() for member in members}
    for member in members:
        for parent in member.parents:
            if parent == PurePosixPath("."):
                break
            ancestor = parent.as_posix()
            if ancestor in names and ancestor not in directories:
                raise ArtifactError(f"archive file is also used as a directory: {ancestor!r}")


def _check_zip_members(infos: Sequence[zipfile.ZipInfo]) -> list[PurePosixPath]:
    for info in infos:
        original = info.orig_filename
        _validate_path(original)
        if original != info.filename:
            raise ArtifactError(f"ZIP member name changed during normalization: {original!r}")
    members = _check_sizes((info.filename, info.file_size) for info in infos)
    _check_ancestor_conflicts(members, directories=set())
    for info in infos:
        if info.flag_bits & 0x1:
            raise ArtifactError(f"encrypted ZIP member: {info.filename}")
        if info.comment or info.extra:
            raise ArtifactError(
                f"ZIP member comments and extra fields are not allowed: {info.filename}"
            )
        if info.compress_type not in {zipfile.ZIP_STORED, zipfile.ZIP_DEFLATED}:
            raise ArtifactError(f"unsupported ZIP compression method: {info.filename}")
        mode = info.external_attr >> 16
        file_type = stat.S_IFMT(mode)
        if stat.S_ISLNK(mode):
            raise ArtifactError(f"symbolic-link ZIP member: {info.filename}")
        if file_type not in {0, stat.S_IFREG, stat.S_IFDIR}:
            raise ArtifactError(f"non-regular ZIP member: {info.filename}")
        if info.file_size and not info.compress_size:
            raise ArtifactError(f"invalid compressed size for ZIP member: {info.filename}")
        if info.compress_size:
            ratio = info.file_size / info.compress_size
            if ratio > MAX_COMPRESSION_RATIO:
                raise ArtifactError(
                    f"ZIP member compression ratio exceeds {MAX_COMPRESSION_RATIO:g}: "
                    f"{info.filename}"
                )
    return members


def _check_tar_members(infos: Sequence[tarfile.TarInfo]) -> list[PurePosixPath]:
    members = _check_sizes((info.name, info.size) for info in infos)
    directories = {PurePosixPath(info.name).as_posix() for info in infos if info.isdir()}
    _check_ancestor_conflicts(members, directories)
    for info in infos:
        if not (info.isfile() or info.isdir()):
            raise ArtifactError(f"linked or non-regular tar member: {info.name}")
    return members


def _check_tar_gzip_envelope(path: Path, members: Sequence[tarfile.TarInfo]) -> None:
    if path.stat().st_size > MAX_ARCHIVE_BYTES:
        raise ArtifactError(f"sdist archive exceeds {MAX_ARCHIVE_BYTES} bytes")
    try:
        with gzip.open(path, "rb") as stream:
            payload = stream.read(MAX_TAR_STREAM_BYTES + 1)
    except (gzip.BadGzipFile, EOFError, OSError) as exc:
        raise ArtifactError(f"sdist gzip stream is invalid: {exc}") from exc
    if len(payload) > MAX_TAR_STREAM_BYTES:
        raise ArtifactError(f"sdist tar stream exceeds {MAX_TAR_STREAM_BYTES} bytes")
    for member in members:
        if not member.isfile():
            continue
        content_end = member.offset_data + member.size
        padded_end = member.offset_data + ((member.size + 511) // 512) * 512
        if any(payload[content_end:padded_end]):
            raise ArtifactError(f"sdist has hidden data in tar padding after {member.name!r}")
    data_end = max(
        (member.offset_data + ((member.size + 511) // 512) * 512 for member in members),
        default=0,
    )
    trailer = payload[data_end:]
    if len(trailer) < 1024 or len(trailer) % 512 or any(trailer):
        raise ArtifactError("sdist has hidden data or invalid padding after the tar members")


def _descriptor_matches(payload: bytes, info: zipfile.ZipInfo) -> bool:
    if len(payload) == 12:
        crc, compressed, uncompressed = struct.unpack("<LLL", payload)
    elif len(payload) == 16 and payload[:4] == b"PK\x07\x08":
        _signature, crc, compressed, uncompressed = struct.unpack("<4sLLL", payload)
    elif len(payload) == 20:
        crc, compressed, uncompressed = struct.unpack("<LQQ", payload)
    elif len(payload) == 24 and payload[:4] == b"PK\x07\x08":
        _signature, crc, compressed, uncompressed = struct.unpack("<4sLQQ", payload)
    else:
        return False
    return crc == info.CRC and compressed == info.compress_size and uncompressed == info.file_size


def _check_local_zip_records(
    path: Path,
    infos: Sequence[zipfile.ZipInfo],
    directory_offset: int,
) -> None:
    ordered = sorted(infos, key=lambda info: info.header_offset)
    if not ordered or ordered[0].header_offset != 0:
        raise ArtifactError("ZIP archive has a preamble before its first member")
    with path.open("rb") as stream:
        for index, info in enumerate(ordered):
            boundary = (
                ordered[index + 1].header_offset if index + 1 < len(ordered) else directory_offset
            )
            stream.seek(info.header_offset)
            header = stream.read(30)
            if len(header) != 30 or header[:4] != b"PK\x03\x04":
                raise ArtifactError(f"invalid local ZIP header for {info.filename!r}")
            (
                _signature,
                _extract_version,
                flags,
                compression,
                _modified_time,
                _modified_date,
                crc,
                compressed_size,
                uncompressed_size,
                name_size,
                extra_size,
            ) = struct.unpack("<4s5H3L2H", header)
            if flags != info.flag_bits or compression != info.compress_type:
                raise ArtifactError(f"local/central ZIP metadata mismatch: {info.filename!r}")
            raw_name = stream.read(name_size)
            local_extra = stream.read(extra_size)
            if local_extra or info.extra:
                raise ArtifactError(f"ZIP extra fields are not allowed: {info.filename!r}")
            encoding = "utf-8" if flags & 0x800 else "cp437"
            try:
                local_name = raw_name.decode(encoding)
            except UnicodeDecodeError as exc:
                raise ArtifactError(
                    f"invalid local ZIP filename encoding: {info.filename!r}"
                ) from exc
            if local_name != info.filename:
                raise ArtifactError(f"local/central ZIP filename mismatch: {info.filename!r}")

            payload_start = info.header_offset + 30 + name_size + extra_size
            payload_end = payload_start + info.compress_size
            if payload_end > boundary:
                raise ArtifactError(f"overlapping ZIP member records: {info.filename!r}")
            stream.seek(payload_start)
            compressed_payload = stream.read(info.compress_size)
            if len(compressed_payload) != info.compress_size:
                raise ArtifactError(f"truncated ZIP member payload: {info.filename!r}")
            if info.compress_type == zipfile.ZIP_STORED:
                expanded = compressed_payload
            else:
                decompressor = zlib.decompressobj(-15)
                try:
                    expanded = decompressor.decompress(compressed_payload, MAX_MEMBER_BYTES + 1)
                    expanded += decompressor.flush()
                except zlib.error as exc:
                    raise ArtifactError(
                        f"invalid deflate stream for {info.filename!r}: {exc}"
                    ) from exc
                if not decompressor.eof or decompressor.unused_data or decompressor.unconsumed_tail:
                    raise ArtifactError(
                        f"deflate stream has hidden or trailing data: {info.filename!r}"
                    )
            if len(expanded) != info.file_size or zlib.crc32(expanded) & 0xFFFFFFFF != info.CRC:
                raise ArtifactError(f"local ZIP payload metadata mismatch: {info.filename!r}")

            if flags & 0x08:
                stream.seek(payload_end)
                descriptor = stream.read(boundary - payload_end)
                if not _descriptor_matches(descriptor, info):
                    raise ArtifactError(
                        f"invalid or non-contiguous ZIP data descriptor: {info.filename!r}"
                    )
            else:
                if payload_end != boundary:
                    raise ArtifactError(
                        f"hidden data between ZIP member records: {info.filename!r}"
                    )
                if (
                    crc != info.CRC
                    or compressed_size != info.compress_size
                    or uncompressed_size != info.file_size
                ):
                    raise ArtifactError(f"local ZIP sizes or CRC mismatch: {info.filename!r}")


def _check_zip_envelope(path: Path, archive: zipfile.ZipFile) -> int:
    size = path.stat().st_size
    if size > MAX_ARCHIVE_BYTES:
        raise ArtifactError(f"ZIP archive exceeds {MAX_ARCHIVE_BYTES} bytes")
    if archive.comment:
        raise ArtifactError("ZIP archive comments are not allowed")
    if size < 22:
        raise ArtifactError("ZIP archive is too small to contain an end record")

    with path.open("rb") as stream:
        if stream.read(4) != b"PK\x03\x04":
            raise ArtifactError("ZIP archive has a preamble or no initial local file header")
        stream.seek(size - 22)
        eocd = stream.read(22)
        if len(eocd) != 22 or eocd[:4] != b"PK\x05\x06":
            raise ArtifactError("ZIP archive has a comment or trailing data")
        (
            _signature,
            disk_number,
            directory_disk,
            entries_on_disk,
            total_entries,
            directory_size,
            directory_offset,
            comment_size,
        ) = struct.unpack("<4s4H2LH", eocd)
        if comment_size:
            raise ArtifactError("ZIP archive comments are not allowed")

        eocd_offset = size - 22
        zip64 = (
            disk_number == 0xFFFF
            or directory_disk == 0xFFFF
            or entries_on_disk == 0xFFFF
            or total_entries == 0xFFFF
            or directory_size == 0xFFFFFFFF
            or directory_offset == 0xFFFFFFFF
        )
        if zip64:
            locator_offset = eocd_offset - 20
            if locator_offset < 56:
                raise ArtifactError("ZIP64 end records are incomplete")
            stream.seek(locator_offset)
            locator = stream.read(20)
            if len(locator) != 20 or locator[:4] != b"PK\x06\x07":
                raise ArtifactError("ZIP64 locator is missing")
            _locator_signature, _zip64_disk, zip64_offset, _total_disks = struct.unpack(
                "<4sLQL", locator
            )
            stream.seek(zip64_offset)
            zip64_record = stream.read(56)
            if len(zip64_record) != 56 or zip64_record[:4] != b"PK\x06\x06":
                raise ArtifactError("ZIP64 end record is missing")
            record_size = struct.unpack_from("<Q", zip64_record, 4)[0]
            if zip64_offset + 12 + record_size != locator_offset:
                raise ArtifactError("ZIP64 end records contain hidden or trailing data")
            directory_size = struct.unpack_from("<Q", zip64_record, 40)[0]
            directory_offset = struct.unpack_from("<Q", zip64_record, 48)[0]
            disk_number = struct.unpack_from("<L", zip64_record, 16)[0]
            directory_disk = struct.unpack_from("<L", zip64_record, 20)[0]
            entries_on_disk = struct.unpack_from("<Q", zip64_record, 24)[0]
            total_entries = struct.unpack_from("<Q", zip64_record, 32)[0]
            directory_end = zip64_offset
        else:
            directory_end = eocd_offset
        if (
            disk_number != 0
            or directory_disk != 0
            or entries_on_disk != total_entries
            or total_entries != len(archive.infolist())
        ):
            raise ArtifactError("multi-disk or inconsistent ZIP directory is not allowed")
        if directory_offset + directory_size != directory_end:
            raise ArtifactError("ZIP central directory is not contiguous with its end records")

    return int(directory_offset)


def _check_sdist(path: Path, version: str) -> None:
    expected_root = f"workbooklens-{version}"
    try:
        with tarfile.open(path, "r:gz") as archive:
            raw_members = archive.getmembers()
            members = _check_tar_members(raw_members)
            pkg_info_name = f"{expected_root}/PKG-INFO"
            pkg_info_members = [
                member for member in raw_members if member.name == pkg_info_name and member.isfile()
            ]
            if len(pkg_info_members) != 1:
                raise ArtifactError("sdist must contain exactly one root PKG-INFO file")
            extracted = archive.extractfile(pkg_info_members[0])
            if extracted is None:
                raise ArtifactError("cannot read sdist PKG-INFO")
            pkg_info = extracted.read(MAX_MEMBER_BYTES + 1)
            if len(pkg_info) > MAX_MEMBER_BYTES:
                raise ArtifactError("sdist PKG-INFO exceeds the member-size limit")
    except (tarfile.TarError, OSError) as exc:
        raise ArtifactError(f"cannot read sdist archive: {exc}") from exc
    _check_tar_gzip_envelope(path, raw_members)
    _distribution_metadata(pkg_info, "PKG-INFO", version)
    total_size = sum(member.size for member in raw_members)
    archive_size = path.stat().st_size
    if archive_size and total_size / archive_size > MAX_COMPRESSION_RATIO:
        raise ArtifactError(f"sdist compression ratio exceeds {MAX_COMPRESSION_RATIO:g}")
    relative: list[PurePosixPath] = []
    for member in members:
        if not member.parts or member.parts[0] != expected_root:
            raise ArtifactError(f"sdist member is outside {expected_root!r}: {member}")
        if len(member.parts) > 1:
            relative.append(PurePosixPath(*member.parts[1:]))
    unexpected = sorted(
        {member.parts[0] for member in relative if member.parts[0] not in SDIST_TOP_LEVEL}
    )
    if unexpected:
        raise ArtifactError("unexpected sdist top-level entries: " + ", ".join(unexpected))
    required = {
        "LICENSE",
        "PKG-INFO",
        "README.md",
        "packaging/windows/README-PORTABLE.txt",
        "packaging/windows/Start-WorkbookLens.cmd",
        "packaging/windows/WorkbookLens.iss",
        "packaging/windows/WorkbookLens.spec",
        "packaging/windows/entry.py",
        "pyproject.toml",
        "scripts/action_scan.py",
        "scripts/build_installer_windows.py",
        "scripts/build_portable_windows.py",
        "scripts/check_installer_artifact.py",
        "scripts/check_portable_artifact.py",
        "scripts/check_release_artifacts.py",
        "scripts/smoke_installer_windows.py",
        "scripts/smoke_portable.py",
        "src/workbooklens/__init__.py",
        "src/workbooklens/console.py",
        "src/workbooklens/conversion.py",
        "src/workbooklens/web/launcher.py",
    }
    names = {member.as_posix() for member in relative}
    missing = sorted(required - names)
    if missing:
        raise ArtifactError("sdist is missing required files: " + ", ".join(missing))


def _check_wheel(path: Path, version: str) -> None:
    dist_info = f"workbooklens-{version}.dist-info"
    with zipfile.ZipFile(path) as archive:
        directory_offset = _check_zip_envelope(path, archive)
        infos = archive.infolist()
        members = _check_zip_members(infos)
        _check_local_zip_records(path, infos, directory_offset)
        bad_member = archive.testzip()
        if bad_member is not None:
            raise ArtifactError(f"wheel CRC check failed for: {bad_member}")
        allowed_roots = {"workbooklens", dist_info}
        unexpected = sorted({member.parts[0] for member in members} - allowed_roots)
        if unexpected:
            raise ArtifactError("unexpected wheel top-level entries: " + ", ".join(unexpected))
        names = {member.as_posix() for member in members}
        required = {
            "workbooklens/__init__.py",
            "workbooklens/console.py",
            "workbooklens/conversion.py",
            "workbooklens/diff/templates/diff.html.j2",
            "workbooklens/reports/templates/scan.html.j2",
            "workbooklens/web/launcher.py",
            f"{dist_info}/METADATA",
            f"{dist_info}/RECORD",
            f"{dist_info}/WHEEL",
            f"{dist_info}/licenses/LICENSE",
        }
        missing = sorted(required - names)
        if missing:
            raise ArtifactError("wheel is missing required files: " + ", ".join(missing))
        _check_wheel_metadata_and_record(archive, infos, dist_info, version)


def _check_wheel_metadata_and_record(
    archive: zipfile.ZipFile,
    infos: Sequence[zipfile.ZipInfo],
    dist_info: str,
    version: str,
) -> None:
    metadata_name = f"{dist_info}/METADATA"
    wheel_name = f"{dist_info}/WHEEL"
    record_name = f"{dist_info}/RECORD"
    _distribution_metadata(archive.read(metadata_name), "wheel METADATA", version)

    wheel_message = BytesParser(policy=email.policy.default).parsebytes(archive.read(wheel_name))
    wheel_version = str(wheel_message.get("Wheel-Version", "")).strip()
    root_is_purelib = str(wheel_message.get("Root-Is-Purelib", "")).strip().casefold()
    tags = {str(tag).strip() for tag in wheel_message.get_all("Tag", [])}
    if wheel_version != "1.0" or root_is_purelib != "true" or "py3-none-any" not in tags:
        raise ArtifactError(
            "wheel WHEEL metadata must declare Wheel-Version 1.0, "
            "Root-Is-Purelib true, and Tag py3-none-any"
        )

    try:
        record_text = archive.read(record_name).decode("utf-8")
        rows = list(csv.reader(StringIO(record_text, newline="")))
    except (UnicodeError, csv.Error) as exc:
        raise ArtifactError(f"cannot parse wheel RECORD: {exc}") from exc
    record_rows: dict[str, tuple[str, str]] = {}
    for row in rows:
        if len(row) != 3:
            raise ArtifactError(f"wheel RECORD row must have three columns: {row!r}")
        name, digest, size = row
        if name in record_rows:
            raise ArtifactError(f"duplicate wheel RECORD path: {name!r}")
        record_rows[name] = (digest, size)

    archive_names = {info.filename for info in infos}
    if set(record_rows) != archive_names:
        missing_rows = sorted(archive_names - set(record_rows))
        extra_rows = sorted(set(record_rows) - archive_names)
        raise ArtifactError(
            f"wheel RECORD coverage mismatch; missing={missing_rows!r}, extra={extra_rows!r}"
        )
    for info in infos:
        digest, size = record_rows[info.filename]
        if info.filename == record_name:
            if digest or size:
                raise ArtifactError("wheel RECORD must leave its own hash and size empty")
            continue
        if not digest.startswith("sha256="):
            raise ArtifactError(f"wheel RECORD must use sha256 for {info.filename!r}")
        encoded_digest = digest.removeprefix("sha256=")
        expected_digest = (
            base64.urlsafe_b64encode(hashlib.sha256(archive.read(info)).digest())
            .rstrip(b"=")
            .decode("ascii")
        )
        if encoded_digest != expected_digest:
            raise ArtifactError(f"wheel RECORD hash mismatch for {info.filename!r}")
        if size != str(info.file_size):
            raise ArtifactError(f"wheel RECORD size mismatch for {info.filename!r}")


def _is_link_or_reparse_point(path: Path) -> bool:
    if path.is_symlink():
        return True
    attributes = getattr(path.lstat(), "st_file_attributes", 0)
    reparse_flag = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0)
    return bool(reparse_flag and attributes & reparse_flag)


def check_distribution(directory: Path, version: str) -> None:
    expected_wheel = f"workbooklens-{version}-py3-none-any.whl"
    expected_sdist = f"workbooklens-{version}.tar.gz"
    expected_names = {expected_wheel, expected_sdist}
    if not directory.is_dir():
        raise ArtifactError(f"release directory does not exist: {directory}")
    resolved_directory = directory.resolve()
    entries = sorted(directory.iterdir(), key=lambda entry: entry.name)
    unsafe_entries = [
        entry.name
        for entry in entries
        if (
            _is_link_or_reparse_point(entry)
            or not entry.is_file()
            or entry.resolve().parent != resolved_directory
        )
    ]
    if unsafe_entries:
        raise ArtifactError(
            "release directory contains linked, external, or non-file entries: "
            + ", ".join(unsafe_entries)
        )
    actual_names = {entry.name for entry in entries}
    generated_ignore = directory / ".gitignore"
    if generated_ignore.name in actual_names:
        try:
            content = generated_ignore.read_bytes()
        except OSError as exc:
            raise ArtifactError(f"cannot read uv-generated {generated_ignore.name}: {exc}") from exc
        if content not in UV_BUILD_IGNORE_CONTENTS:
            raise ArtifactError(
                f"uv-generated {generated_ignore.name} has unexpected content: {content!r}"
            )
        actual_names.remove(generated_ignore.name)
    if actual_names != expected_names:
        unexpected = sorted(actual_names - expected_names)
        missing = sorted(expected_names - actual_names)
        details: list[str] = []
        if unexpected:
            details.append("unexpected: " + ", ".join(unexpected))
        if missing:
            details.append("missing: " + ", ".join(missing))
        raise ArtifactError(
            "release directory must contain exactly the expected wheel and sdist"
            + (f" ({'; '.join(details)})" if details else "")
        )
    _check_wheel(directory / expected_wheel, version)
    _check_sdist(directory / expected_sdist, version)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("directory", type=Path)
    parser.add_argument("--version", required=True)
    arguments = parser.parse_args()
    check_distribution(arguments.directory.resolve(), arguments.version)
    print(f"Release artifacts passed allowlist inspection for WorkbookLens {arguments.version}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
