"""Fail a release when wheel or sdist contents escape the public allowlist."""

from __future__ import annotations

import argparse
import tarfile
import zipfile
from collections.abc import Iterable
from pathlib import Path, PurePosixPath

FORBIDDEN_COMPONENTS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "__pycache__",
    "node_modules",
    "venv",
}
FORBIDDEN_SUFFIXES = {".key", ".p12", ".pem", ".pfx", ".pyc", ".pyo"}
SENSITIVE_NAMES = {
    "credentials",
    "credentials.json",
    "id_dsa",
    "id_ed25519",
    "id_rsa",
    "secrets.json",
}
SDIST_TOP_LEVEL = {
    ".github",
    ".gitignore",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "LICENSE",
    "PKG-INFO",
    "README.md",
    "SECURITY.md",
    "action.yml",
    "docs",
    "pyproject.toml",
    "scripts",
    "src",
    "tests",
    "uv.lock",
    "workbooklens.example.yml",
}
MAX_MEMBERS = 2_000
MAX_MEMBER_BYTES = 10 * 1024 * 1024


class ArtifactError(RuntimeError):
    """A built distribution contains unexpected or unsafe material."""


def _validate_path(name: str) -> PurePosixPath:
    if not name or chr(92) in name:
        raise ArtifactError(f"non-portable archive member: {name!r}")
    path = PurePosixPath(name)
    if path.is_absolute() or any(part in {"", ".", ".."} for part in path.parts):
        raise ArtifactError(f"unsafe archive member: {name!r}")
    lowered = [part.lower() for part in path.parts]
    for part in lowered:
        if (
            part in FORBIDDEN_COMPONENTS
            or part.startswith(".venv")
            or part.endswith("-venv")
            or part.startswith(".env")
        ):
            raise ArtifactError(f"forbidden environment/cache path in artifact: {name}")
    basename = lowered[-1]
    if basename in SENSITIVE_NAMES or path.suffix.lower() in FORBIDDEN_SUFFIXES:
        raise ArtifactError(f"possible secret or generated bytecode in artifact: {name}")
    return path


def _check_sizes(members: Iterable[tuple[str, int]]) -> list[PurePosixPath]:
    checked: list[PurePosixPath] = []
    for index, (name, size) in enumerate(members, start=1):
        if index > MAX_MEMBERS:
            raise ArtifactError(f"artifact has more than {MAX_MEMBERS} members")
        if size > MAX_MEMBER_BYTES:
            raise ArtifactError(f"artifact member exceeds {MAX_MEMBER_BYTES} bytes: {name}")
        checked.append(_validate_path(name))
    return checked


def _check_sdist(path: Path, version: str) -> None:
    expected_root = f"workbooklens-{version}"
    with tarfile.open(path, "r:gz") as archive:
        raw_members = archive.getmembers()
        members = _check_sizes((member.name, member.size) for member in raw_members)
    relative: list[PurePosixPath] = []
    for member in members:
        if not member.parts or member.parts[0] != expected_root:
            raise ArtifactError(f"sdist member is outside {expected_root!r}: {member}")
        if len(member.parts) > 1:
            relative.append(PurePosixPath(*member.parts[1:]))
    unexpected = sorted(
        {member.parts[0] for member in relative if member.parts[0] not in SDIST_TOP_LEVEL}
    )
    if unexpected:
        raise ArtifactError("unexpected sdist top-level entries: " + ", ".join(unexpected))
    required = {
        "LICENSE",
        "README.md",
        "pyproject.toml",
        "scripts/action_scan.py",
        "scripts/check_release_artifacts.py",
        "src/workbooklens/__init__.py",
    }
    names = {member.as_posix() for member in relative}
    missing = sorted(required - names)
    if missing:
        raise ArtifactError("sdist is missing required files: " + ", ".join(missing))


def _check_wheel(path: Path, version: str) -> None:
    dist_info = f"workbooklens-{version}.dist-info"
    with zipfile.ZipFile(path) as archive:
        infos = archive.infolist()
        members = _check_sizes((info.filename, info.file_size) for info in infos)
    allowed_roots = {"workbooklens", dist_info}
    unexpected = sorted({member.parts[0] for member in members} - allowed_roots)
    if unexpected:
        raise ArtifactError("unexpected wheel top-level entries: " + ", ".join(unexpected))
    names = {member.as_posix() for member in members}
    required = {
        "workbooklens/__init__.py",
        "workbooklens/diff/templates/diff.html.j2",
        "workbooklens/reports/templates/scan.html.j2",
        f"{dist_info}/METADATA",
        f"{dist_info}/licenses/LICENSE",
    }
    missing = sorted(required - names)
    if missing:
        raise ArtifactError("wheel is missing required files: " + ", ".join(missing))


def check_distribution(directory: Path, version: str) -> None:
    wheels = sorted(directory.glob("*.whl"))
    sdists = sorted(directory.glob("*.tar.gz"))
    if len(wheels) != 1 or len(sdists) != 1:
        raise ArtifactError(
            "release directory must contain exactly one wheel and one .tar.gz sdist"
        )
    expected_wheel = f"workbooklens-{version}-py3-none-any.whl"
    expected_sdist = f"workbooklens-{version}.tar.gz"
    if wheels[0].name != expected_wheel or sdists[0].name != expected_sdist:
        raise ArtifactError(
            f"unexpected distribution names; expected {expected_wheel!r} and {expected_sdist!r}"
        )
    _check_wheel(wheels[0], version)
    _check_sdist(sdists[0], version)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("directory", type=Path)
    parser.add_argument("--version", required=True)
    arguments = parser.parse_args()
    check_distribution(arguments.directory.resolve(), arguments.version)
    print(f"Release artifacts passed allowlist inspection for WorkbookLens {arguments.version}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
